base: hm3d_00732
filepath: 
  - "/checkpoint/notmahi/data/hm3d_semantic/data/versioned_data/hm3d-1.0/hm3d/train/00732-Z2DQddYp1fn/Z2DQddYp1fn.basis.glb"
grid_size: 10
image_size: 512
subsample_prob: 0.2
