base: hm3d_00250
filepath: 
  - "/checkpoint/notmahi/data/hm3d_semantic/data/versioned_data/hm3d-1.0/hm3d/train/00250-U3oQjwTuMX8/U3oQjwTuMX8.basis.glb"
grid_size: 10
image_size: 224
subsample_prob: 0.2
